version: '3.9'
services:
    metabase:
        hostname: metabase-ui-1
        container_name: metabase-ui-1-container
        image: metabase/metabase:latest
        ports:
            - 3000:3000
        environment:
            MB_DB_TYPE: postgres
            MB_DB_DBNAME: metabase-db-1
            MB_DB_PORT: 5432
            MB_DB_USER: root
            MB_DB_PASS: root
            MB_DB_HOST: postgres-metabase-1

            JAVA_TIMEZONE: 'Europe/Vilnius'
        networks:
            - metabase-network-1
        volumes:
            - metabase-ui-1-data:/metabase-data
        healthcheck:
            test: curl --fail -I http://localhost:3000/api/health || exit 1
            interval: 15s
            timeout: 5s
            retries: 5

    postgres:
        hostname: postgres-metabase-1
        container_name: postgres-metabase-1-container
        image: postgres:latest
        environment:
            POSTGRES_DB: metabase-db-1
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        networks:
            - metabase-network-1
        volumes:
            - metabase-db-1-data:/var/lib/postgresql/data

networks:
    metabase-network-1:
        driver: bridge

volumes:
    metabase-ui-1-data:
    metabase-db-1-data:
