const UNIQUE_DIGITS = '0123456789'
const UNIQUE_LOWER_CASE_LETTERS = 'abcdefghijklmnopqrstuvwxyz'
const UNIQUE_UPPER_CASE_LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

const UNIQUE_MIXED_CASE_LETTERS = UNIQUE_LOWER_CASE_LETTERS + UNIQUE_UPPER_CASE_LETTERS

const ALPHANUMERIC_LOWER_CASE_CHAR_SET = UNIQUE_DIGITS + UNIQUE_LOWER_CASE_LETTERS

const ALPHANUMERIC_UPPER_CASE_CHAR_SET = UNIQUE_DIGITS + UNIQUE_UPPER_CASE_LETTERS

const ALPHANUMERIC_MIXED_CASE_CHAR_SET = UNIQUE_DIGITS + UNIQUE_MIXED_CASE_LETTERS

export const characterSets = {
    UNIQUE_DIGITS,
    UNIQUE_LOWER_CASE_LETTERS,
    UNIQUE_UPPER_CASE_LETTERS,
    UNIQUE_MIXED_CASE_LETTERS,
    ALPHANUMERIC_LOWER_CASE_CHAR_SET,
    ALPHANUMERIC_UPPER_CASE_CHAR_SET,
    ALPHANUMERIC_MIXED_CASE_CHAR_SET,
} as const
