export const errorCodes = {
    DUPLICATE_KEY: 11000,
    NAMESPACE_NOT_FOUND: 26,
    COMMAND_NOT_FOUND: 59,
    EXCEEDED_TIME_LIMIT: 50,
    WRITE_CONCERN_FAILED: 64,
    HOST_UNREACHABLE: 6,
    NETWORK_TIMEOUT: 89,
    SHARD_KEY_FOUND: 96,
    INDEX_NOT_FOUND: 27,
    AUTHENTICATION_FAILED: 18,
}
