global:
    scrape_interval: 15s

scrape_configs:
    # This configuration sets up Prometheus to scrape itself every 15 seconds.
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']

    - job_name: 'node_exporter'
      static_configs:
          - targets: ['node_exporter:9100']

    # Postgresql exporter
    # - job_name: 'postgresql'
    #   static_configs:
    #     - targets: ['postgresql_exporter:9187']
